//! Generic (build-time) field help — delivered as hover tooltips on tree nodes.
//!
//! ## Two-tier help architecture
//!
//! HRW provides two kinds of help for understanding IR fields:
//!
//! 1. **Fast tier (this module):** instant, offline, generic. The `///` doc
//!    comments that Rumoca's authors wrote on `rumoca-ir-ast` IR struct fields
//!    are extracted at build time and embedded as `field_help.json`. When you
//!    hover a field in the tree inspector, its doc comment appears as a tooltip
//!    — no network call, no latency. The help is *generic* (it describes what
//!    `def_id` means in general, not why *this particular* `def_id` has *this
//!    particular* value).
//!
//! 2. **Specific tier (the Claude bridge):** contextual, on-demand, slow. When
//!    the user captures a node and asks in the chat, Claude reasons about *why*
//!    this specific value appeared, using the specimen source, the staged IR,
//!    and the Rumoca phase code as context. See `bridge.rs`.
//!
//! ## How field_help.json is generated
//!
//! The `gen_field_help` example (`examples/gen_field_help.rs`) parses the
//! Rumoca IR AST source files, extracts `///` doc comments from struct fields,
//! and writes `src/field_help.json`. This file is checked into the repo and
//! baked into the binary via `include_str!`. Regenerate after a Rumoca update
//! with `cargo run -p hrw --example gen_field_help`.

use std::collections::HashMap;

// The field help table is embedded at compile time via `include_str!`.
// This means the binary is self-contained — no runtime file I/O needed.
// The JSON maps field names (strings) to their doc-comment text (strings).
const FIELD_HELP_JSON: &str = include_str!("field_help.json");

/// Parse the embedded field-help table into a `HashMap<field_name, doc_text>`.
///
/// Returns an empty map if parsing fails (defensive — should never happen since
/// the JSON is generated by our own tooling). Keyed by field name only (v1);
/// a future refinement could disambiguate by owning type for fields whose name
/// appears in multiple IR structs.
pub fn load() -> HashMap<String, String> {
    serde_json::from_str(FIELD_HELP_JSON).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The embedded field_help.json parses and contains entries.
    #[test]
    fn field_help_loads_non_empty() {
        let help = load();
        assert!(!help.is_empty(), "field_help.json should contain entries");
    }

    /// Key IR field names that the tree inspector relies on are present.
    #[test]
    fn field_help_contains_core_ir_fields() {
        let help = load();
        for key in ["def_id", "classes", "components", "equations", "name"] {
            assert!(help.contains_key(key), "field_help missing expected key: {key}");
        }
    }
}
