//! Generic (build-time) field help — delivered as hover tooltips on tree nodes.
//!
//! ## Two-tier help architecture
//!
//! HRW provides two kinds of help for understanding IR fields:
//!
//! 1. **Fast tier (this module):** instant, offline, generic. The `///` doc
//!    comments that Rumoca's authors wrote on `rumoca-ir-ast` IR struct fields
//!    are extracted at build time and embedded as `field_help.json`. When you
//!    hover a field in the tree inspector, its doc comment appears as a tooltip
//!    — no network call, no latency. The help is *generic* (it describes what
//!    `def_id` means in general, not why *this particular* `def_id` has *this
//!    particular* value).
//!
//! 2. **Specific tier (the Claude bridge):** contextual, on-demand, slow. When
//!    the user captures a node and asks in the chat, Claude reasons about *why*
//!    this specific value appeared, using the specimen source, the staged IR,
//!    and the Rumoca phase code as context. See `bridge.rs`.
//!
//! ## How field_help.json is generated
//!
//! The `gen_field_help` example (`examples/gen_field_help.rs`) parses the
//! Rumoca IR AST source files, extracts `///` doc comments from struct fields,
//! and writes `src/field_help.json`. This file is checked into the repo and
//! baked into the binary via `include_str!`. Regenerate after a Rumoca update
//! with `cargo run -p hrw --example gen_field_help`.

use std::collections::HashMap;

/// IR crates whose `///` field docs are harvested into `field_help.json`.
///
/// **Lives here rather than in `gen_field_help` so a test can reach it.** The list is a
/// fact about which stages have in-app help; the example is only the tool that acts on it.
///
/// It fell a stage behind for weeks: DAE got a tab, `rumoca-ir-dae` was not added, and the
/// pane rendered with no field help while Rumoca already carried 290 lines of `///` docs
/// for it. Nothing failed, because a missing tooltip is invisible.
/// [`tests::every_ir_dependency_is_harvested_for_field_help`] derives the requirement
/// from `Cargo.toml` so the next `rumoca-ir-*` dependency cannot be forgotten.
pub const IR_CRATES: &[&str] = &["rumoca-ir-ast", "rumoca-ir-flat", "rumoca-ir-dae"];

// The field help table is embedded at compile time via `include_str!`.
// This means the binary is self-contained — no runtime file I/O needed.
// The JSON maps field names (strings) to their doc-comment text (strings).
const FIELD_HELP_JSON: &str = include_str!("field_help.json");

/// Parse the embedded field-help table into a `HashMap<field_name, doc_text>`.
///
/// Returns an empty map if parsing fails (defensive — should never happen since
/// the JSON is generated by our own tooling). Keyed by field name only (v1);
/// a future refinement could disambiguate by owning type for fields whose name
/// appears in multiple IR structs.
pub fn load() -> HashMap<String, String> {
    serde_json::from_str(FIELD_HELP_JSON).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The embedded field_help.json parses and contains entries.
    #[test]
    fn field_help_loads_non_empty() {
        let help = load();
        assert!(!help.is_empty(), "field_help.json should contain entries");
    }

    /// Key IR field names that the tree inspector relies on are present.
    #[test]
    fn field_help_contains_core_ir_fields() {
        let help = load();
        for key in ["def_id", "classes", "components", "equations", "name"] {
            assert!(
                help.contains_key(key),
                "field_help missing expected key: {key}"
            );
        }
    }

    /// Every `rumoca-ir-*` crate HRW depends on is harvested for field help.
    ///
    /// # What this prevents, and why nothing noticed for weeks
    ///
    /// [`IR_CRATES`] listed only `rumoca-ir-ast` and `rumoca-ir-flat`, with a note saying
    /// to extend it "as later stages get their own tabs". The tabs arrived; the list did
    /// not follow. So the DAE pane offered **no field help at all** while
    /// `rumoca-ir-dae` already carried 290 lines of `///` docs — the answers existed and
    /// HRW was not asking for them.
    ///
    /// **A missing tooltip is invisible.** Nothing rendered wrong, no test failed, and the
    /// loss only surfaced when Doug said he needed to learn the IR and went looking at
    /// the stage Rumoca documents best.
    ///
    /// Derived from `Cargo.toml` rather than a second hand-written list, because a
    /// hand-written one is the thing that just rotted.
    #[test]
    fn every_ir_dependency_is_harvested_for_field_help() {
        let manifest = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"))
            .expect("hrw/Cargo.toml");

        let mut depended: Vec<String> = Vec::new();
        for line in manifest.lines() {
            let t = line.trim();
            if t.starts_with('#') {
                continue;
            }
            if let Some((name, _)) = t.split_once('=') {
                let name = name.trim();
                if name.starts_with("rumoca-ir-") && !depended.iter().any(|d| d == name) {
                    depended.push(name.to_owned());
                }
            }
        }

        assert!(
            depended.len() >= 3,
            "only {} rumoca-ir-* dependencies were found in Cargo.toml \u{2014} the scan is \
             broken, which looks like success",
            depended.len(),
        );

        let missed: Vec<&String> = depended
            .iter()
            .filter(|d| !IR_CRATES.contains(&d.as_str()))
            .collect();
        assert!(
            missed.is_empty(),
            "HRW depends on {missed:?} but does not harvest their `///` field docs, so \
             those stages render with no field help. Add them to `field_help::IR_CRATES` \
             and re-run `cargo run -p hrw --example gen_field_help`.",
        );
    }
}
